### ISSUE TITLE
Wiki : Errors in state table

### ISSUE THREAD

**Issue by csBlueChip** [jonthysell/SegaController#4]
Hi,

First off - great work - thanks :)

I just noticed (in the Wiki) that states {0, 1} in the 6-button Genesis State Table are blank!?
...should they not be the same as states {2, 3}?
IE. (0==2) and (1==3)

QV. _"The first 4 states (0-3) report buttons like a 3-button controller. Games programmed to read a 3-button controller once per frame still work as expected."_ 

IE.

State | Select (Pin 7) | Pin 1 | Pin 2 | Pin 3 | Pin 4 | Pin 6 | Pin 9
-- | -- | -- | -- | -- | -- | -- | --
0 | LOW |   |   | * | * | A | Start
1 | HIGH | Up | Down | Left | Right | B | C
2 | LOW |   |   | * | * | A | Start
3 | HIGH | Up | Down | Left | Right | B | C

Also.
+ Do we have more information on states {7, 8} for UNofficial controllers?
+ Are all UNofficial controllers all the same, or are there some/many variations?
+ In case the answer to the previous two questions is does not imply an obvious answer ...What game might use these UNofficial readings?

BC

**Comment by jonthysell** [comment]
Yes, technically the blanks are incorrect - you can get button states via the pins at those times. I just didn't think it necessary to try and read the buttons more than once per cycle in my code, and in my my testing, IIRC, it was much more stable to only read the pins on the state changes listed.
